/*
 * Filename: project_zero.c
 *
 * Description: This is the simple_central example modified to receive
 * data over BLE at a high throughput.
 *
 *
 * Copyright (C) 2015-2017 Texas Instruments Incorporated - http://www.ti.com/
 *
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 Generated by:
 BDS version: 1.1.3139.0
 Plugin:      Texas Instruments BLE SDK GATT Server plugin 1.0.9
 Time:        Fri Sep 15 2017 01:07:25 GMT+07:00
 *****************************************************************************/

/*
 * INCLUDES
 */
#include <string.h>

//#define xdc_runtime_Log_DISABLE_ALL 1  // Add to disable logs from this file

#include <ti/sysbios/knl/Task.h>
#include <ti/sysbios/knl/Event.h>
#include <ti/sysbios/knl/Queue.h>
#include <ti/sysbios/knl/Clock.h>

#include <ti/drivers/PIN.h>
#include <ti/display/Display.h>

#include <xdc/runtime/Log.h>
#include <xdc/runtime/Diags.h>
#ifdef UARTLOG_ENABLE
#  include "UartLog.h"
#endif

/* This Header file contains all BLE API and icall structure definition */
#include "icall_ble_api.h"
#include <icall.h>

#include <osal_snv.h>
#include <peripheral.h>
#include <devinfoservice.h>

#include "util.h"

#include "Board.h"
#include "project_zero.h"
#include "GeneralDef.h"
// Bluetooth Developer Studio services
#include "vogatt.h"

//#include <ti/drivers/PWM.h>
#include <ti/drivers/timer/GPTimerCC26XX.h>
#include <ti/drivers/crypto/CryptoCC26XX.h>
//#include <ti/drivers/pdm/PDMCC26XX.h>
//#include "PDMCC26XX.h"

#include <ti/sysbios/BIOS.h>
#include <ti/sysbios/knl/Mailbox.h>

#include <xdc/runtime/Memory.h>
#include <xdc/runtime/Error.h>

#//include "codec/SitCodec.h"
#include "codec/SitADPCM.h"

#include <driverlib/vims.h>
#include <driverlib/flash.h>
#include <ti/sysbios/family/arm/m3/Hwi.h>

/*********************************************************************
 * CONSTANTS
 */
// Advertising interval when device is discoverable (units of 625us, 160=100ms)
#define DEFAULT_ADVERTISING_INTERVAL          160

// Limited discoverable mode advertises for 30.72s, and then stops
// General discoverable mode advertises indefinitely
#define DEFAULT_DISCOVERABLE_MODE             GAP_ADTYPE_FLAGS_GENERAL

// Default pass-code used for pairing.
#define DEFAULT_PASSCODE                      0

// Task configuration
#define PRZ_TASK_PRIORITY                     1

#ifndef PRZ_TASK_STACK_SIZE
#define PRZ_TASK_STACK_SIZE                   1300
#endif

// Internal Events for RTOS application
#define PRZ_ICALL_EVT                         ICALL_MSG_EVENT_ID  // Event_Id_31
#define PRZ_QUEUE_EVT                         UTIL_QUEUE_EVENT_ID // Event_Id_30
#define PRZ_STATE_CHANGE_EVT                  Event_Id_00
#define PRZ_CHAR_CHANGE_EVT                   Event_Id_01
#define PRZ_PERIODIC_EVT                      Event_Id_02
#define PRZ_APP_MSG_EVT                       Event_Id_03
#define PRZ_CONN_EVT_END_EVT                  Event_Id_30

#define PRZ_ALL_EVENTS                       (PRZ_ICALL_EVT        | \
                                              PRZ_QUEUE_EVT        | \
                                              PRZ_STATE_CHANGE_EVT | \
                                              PRZ_CHAR_CHANGE_EVT  | \
                                              PRZ_PERIODIC_EVT     | \
                                              PRZ_APP_MSG_EVT      | \
                                              PRZ_CONN_EVT_END_EVT)

#define BUFFERSIZE                            320
#define SAMP_FREQ                             8000
//#define PWM_PERIOD                            32000

#define LED_COUNTER                           10


/*********************************************************************
 * TYPEDEFS
 */
// Types of messages that can be sent to the user application task from other
// tasks or interrupts. Note: Messages from BLE Stack are sent differently.
typedef enum
{
  APP_MSG_SERVICE_WRITE = 0,   /* A characteristic value has been written       */
  APP_MSG_SERVICE_CFG,         /* A characteristic configuration has changed    */
  APP_MSG_UPDATE_CHARVAL,      /* Request from ourselves to update a value      */
  APP_MSG_GAP_STATE_CHANGE,    /* The GAP / connection state has changed        */
  APP_MSG_BUTTON_DEBOUNCED,    /* A button has been debounced with new value    */
  APP_MSG_SEND_PASSCODE,       /* A pass-code/PIN is requested during pairing   */
  APP_MSG_SEND_VOICE_SAMP,     /* Request from app to send voice samples to BLE */
  APP_MSG_GET_VOICE_SAMP,
} app_msg_types_t;

// Struct for messages sent to the application task
typedef struct
{
  Queue_Elem       _elem;
  app_msg_types_t  type;
  uint8_t          pdu[];
} app_msg_t;

// Struct for messages about characteristic data
typedef struct
{
  uint16_t svcUUID; // UUID of the service
  uint16_t dataLen; //
  uint8_t  paramID; // Index of the characteristic
  uint8_t  data[];  // Flexible array member, extended to malloc - sizeof(.)
} char_data_t;

// Struct for message about sending/requesting passcode from peer.
typedef struct
{
  uint16_t connHandle;
  uint8_t  uiInputs;
  uint8_t  uiOutputs;
  uint32   numComparison;
} passcode_req_t;

// Struct for message about button state
typedef struct
{
  PIN_Id   pinId;
  uint8_t  state;
} button_state_t;


/*********************************************************************
 * LOCAL VARIABLES
 */

// Entity ID globally used to check for source and/or destination of messages
static ICall_EntityID selfEntity;

// Sync handle globally used to post events to the application thread
static ICall_SyncHandle syncEvent;

// Queue object used for application messages.
static Queue_Struct applicationMsgQ;
static Queue_Handle hApplicationMsgQ;

// Clock structs for periodic notification example
static Clock_Struct v_STREAM_OUTPUT_clock;

// Task configuration
Task_Struct przTask;
Char przTaskStack[PRZ_TASK_STACK_SIZE];


// GAP - SCAN RSP data (max size = 31 bytes)
static uint8_t scanRspData[] =
{
  // No scan response data provided.
  0x00 // Placeholder to keep the compiler happy.
};

// GAP - Advertisement data (max size = 31 bytes, though this is
// best kept short to conserve power while advertisting)
static uint8_t advertData[] =
{
  // Flags; this sets the device to use limited discoverable
  // mode (advertises for 30 seconds at a time) or general
  // discoverable mode (advertises indefinitely), depending
  // on the DEFAULT_DISCOVERY_MODE define.
  0x02,   // length of this data
  GAP_ADTYPE_FLAGS,
  DEFAULT_DISCOVERABLE_MODE | GAP_ADTYPE_FLAGS_BREDR_NOT_SUPPORTED,

  // complete name
  14,
  GAP_ADTYPE_LOCAL_NAME_COMPLETE,
  'C', 'I', 'T', ' ', 'H', 'a', 'n', 'd', 's', 'F', 'r', 'e', 'e','2',

};

// GAP GATT Attributes
static uint8_t attDeviceName[GAP_DEVICE_NAME_LEN] = "CIT HandsFree2";

// Globals used for ATT Response retransmission
static gattMsgEvent_t *pAttRsp = NULL;
static uint8_t rspTxRetry = 0;

// Global display handle
Display_Handle dispHandle;

// Global pin's handle ans status
PIN_Config ledPinTable[] = {
  Board_RLED | PIN_GPIO_OUTPUT_EN | PIN_GPIO_LOW | PIN_PUSHPULL | PIN_DRVSTR_MAX,
  Board_GLED | PIN_GPIO_OUTPUT_EN | PIN_GPIO_LOW | PIN_PUSHPULL | PIN_DRVSTR_MAX,
  PIN_TERMINATE
};
static PIN_Handle ledPinHandle;
static PIN_State ledPinState;

static GPTimerCC26XX_Params tim_params;
static GPTimerCC26XX_Handle tim_hdl = NULL;

//static PWM_Handle pwm_hdl = NULL;
//static PWM_Params pwm_params;

static Mailbox_Handle mailbox;

static CryptoCC26XX_Handle crypto_handle;
//static CryptoCC26XX_AESECB_Transaction trans;
static int32_t key_index;
static uint8_t key[] = {0x2C, 0x7E, 0x15, 0x16, 0x28, 0xAD, 0xD2, 0xA6,
                    0xAB, 0xA5, 0x15, 0x88, 0x09, 0xCF, 0x2F, 0x3C};
//static int32_t crypto_status;

#include <math.h>
#include "I2S/I2SCC26XX.h"
#define M_PI        3.14159265358979323846
#define I2S_SAMP_PER_FRAME    80

#define I2S_BUF     sizeof(int16_t) * (I2S_SAMP_PER_FRAME *   \
                                        I2SCC26XX_QUEUE_SIZE * 2)

static void bufRdy_callback(I2SCC26XX_Handle handle, I2SCC26XX_StreamNotification *pStreamNotification);

#define I2S_MEM_BASE (GPRAM_BASE + FlashSectorSizeGet())
#define AUDIO_DUPLEX_STREAM_TYPE_NONE               AUDIO_DUPLEX_CMD_STOP
#define AUDIO_DUPLEX_STREAM_TYPE_ADPCM              AUDIO_DUPLEX_CMD_START
static void AudioDuplex_disableCache();
static I2SCC26XX_StreamNotification i2sStream;
static void AudioDuplex_i2sCallbackFxn(I2SCC26XX_Handle handle,
                                    I2SCC26XX_StreamNotification *notification);

static I2SCC26XX_BufferRequest bufferRequest;
static I2SCC26XX_BufferRelease bufferRelease;
static I2SCC26XX_StreamNotification i2sStream;
static I2SCC26XX_Params i2sParams =
{
    .requestMode            = I2SCC26XX_CALLBACK_MODE,
    .ui32requestTimeout     = BIOS_WAIT_FOREVER,
    .callbackFxn            = bufRdy_callback,//AudioDuplex_i2sCallbackFxn,
    .blockSize              = 0,
    .pvContBuffer           = NULL,
    .ui32conBufTotalSize    = 0,
    .pvContMgtBuffer        = NULL,
    .ui32conMgtBufTotalSize = 0,
    .currentStream          = &i2sStream
};

static I2SCC26XX_Handle i2sHandle = (I2SCC26XX_Handle)&(I2SCC26XX_config);

//static unsigned char i2s_val = 1;
static int16_t *audio_decoded = NULL;
static uint8_t *i2sContMgtBuffer = NULL;
static bool i2sStreamInProgress = false;
Bool bufferReady = false;

/*
static PDMCC26XX_BufferRequest bufferRequest;
static PDMCC26XX_Params pdmParams;
static PDMCC26XX_Handle pdmHandle = (PDMCC26XX_Handle)&(PDMCC26XX_config);
static const uint16_t returnBufferSize = 320;
*/

//static bool status_pdm;
static unsigned char pdm_val = 1;
//static gsit_state encoder, decoder;

static struct ADPCMstate encoder_adpcm, decoder_adpcm;

static int stream_on = 0;

static uint32_t green_counter = 0;
static uint32_t red_counter = 0;

static uint32_t tmr_counter = 0;
static uint32_t i2s_counter = 0;


//#define BT_PACKET_DEBUG
#ifdef BT_PACKET_DEBUG
    #define TEST_SIZE 255
    static uint8_t rx_data[TEST_SIZE];
    static uint8_t rx_counter = 0;
    static uint16_t number_of_losts = 0;
    static uint16_t packets_lost = 0;
#endif
/*********************************************************************
 * LOCAL FUNCTIONS
 */

static void ProjectZero_init( void );
static void ProjectZero_taskFxn(UArg a0, UArg a1);

static void user_processApplicationMessage(app_msg_t *pMsg);
static uint8_t ProjectZero_processStackMsg(ICall_Hdr *pMsg);
static uint8_t ProjectZero_processGATTMsg(gattMsgEvent_t *pMsg);

static void ProjectZero_sendAttRsp(void);
static uint8_t ProjectZero_processGATTMsg(gattMsgEvent_t *pMsg);
static void ProjectZero_freeAttRsp(uint8_t status);

static void user_processGapStateChangeEvt(gaprole_States_t newState);
static void user_gapStateChangeCB(gaprole_States_t newState);
static void user_gapBondMgr_passcodeCB(uint8_t *deviceAddr, uint16_t connHandle,
                                       uint8_t uiInputs, uint8_t uiOutputs, uint32 numComparison);
static void user_gapBondMgr_pairStateCB(uint16_t connHandle, uint8_t state,
                                        uint8_t status);


// Generic callback handlers for value changes in services.
static void user_service_ValueChangeCB( uint16_t connHandle, uint16_t svcUuid, uint8_t paramID, uint8_t *pValue, uint16_t len );
static void user_service_CfgChangeCB( uint16_t connHandle, uint16_t svcUuid, uint8_t paramID, uint8_t *pValue, uint16_t len );

// Task context handlers for generated services.
static void user_Vogatt_ValueChangeHandler(char_data_t *pCharData);
static void user_Vogatt_CfgChangeHandler(char_data_t *pCharData);

// Task handler for sending notifications.
static void user_updateCharVal(char_data_t *pCharData);

// Utility functions
static void user_enqueueRawAppMsg(app_msg_types_t appMsgType, uint8_t *pData, uint16_t len );
static void user_enqueueCharDataMsg( app_msg_types_t appMsgType, uint16_t connHandle,
                                       uint16_t serviceUUID, uint8_t paramID,
                                       uint8_t *pValue, uint16_t len );

static char *Util_getLocalNameStr(const uint8_t *data);
static char *Util_convertArrayToHexString(uint8_t const *src, uint8_t src_len,
                                          uint8_t *dst, uint8_t dst_len);

// Voice handle functions
static void voice_hdl_init(void);
static void timer_callback(GPTimerCC26XX_Handle handle, GPTimerCC26XX_IntMask interruptMask);
static void start_voice_handle(void);
static void stop_voice_handle(void);
//static void bufRdy_callback(PDMCC26XX_Handle handle, PDMCC26XX_StreamNotification *pStreamNotification);
static void *SA_audioMalloc(uint_least16_t size);
static void SA_audioFree(void *msg, size_t size);
static void pdm_samp_hdl(void);


#define ADCBUFSIZE      I2S_SAMP_PER_FRAME//80
#define SAMPFREQ        8000

static ADCBuf_Handle adc_hdl;
static ADCBuf_Params adc_params;
static ADCBuf_Conversion adc_conversion;
static int16_t samp_buf1[ADCBUFSIZE];
static int16_t samp_buf2[ADCBUFSIZE];
static int16_t adc_data[ADCBUFSIZE];
static Bool adc_buf_ready = false;

void adc_callback(ADCBuf_Handle handle, ADCBuf_Conversion *conversion,
                  void *completedADCBuffer, uint32_t completedChannel);
/*********************************************************************
 * PROFILE CALLBACKS
 */

// GAP Role Callbacks
static gapRolesCBs_t user_gapRoleCBs =
{
  user_gapStateChangeCB     // Profile State Change Callbacks
};

// GAP Bond Manager Callbacks
static gapBondCBs_t user_bondMgrCBs =
{
  user_gapBondMgr_passcodeCB, // Passcode callback
  user_gapBondMgr_pairStateCB // Pairing / Bonding state Callback
};

/*
 * Callbacks in the user application for events originating from BLE services.
 */
// Service callback structure for registering our handlers with the service
// VoGATT callback handler.
// The type VoGATTCBs_t is defined in VoGATT.h
static VogattCBs_t user_VoGATTCBs =
{
  .pfnChangeCb    = user_service_ValueChangeCB, // Characteristic value change callback handler
  .pfnCfgChangeCb = user_service_CfgChangeCB, // Noti/ind configuration callback handler
};

/*********************************************************************
 * PUBLIC FUNCTIONS
 */

/*
 * @brief   Task creation function for the user task.
 *
 * @param   None.
 *
 * @return  None.
 */
void ProjectZero_createTask(void)
{
  Task_Params taskParams;

  // Configure task
  Task_Params_init(&taskParams);
  taskParams.stack = przTaskStack;
  taskParams.stackSize = PRZ_TASK_STACK_SIZE;
  taskParams.priority = PRZ_TASK_PRIORITY;

  Task_construct(&przTask, ProjectZero_taskFxn, &taskParams, NULL);
}

/*
 * @brief   Called before the task loop and contains application-specific
 *          initialization of the BLE stack, hardware setup, power-state
 *          notification if used, and BLE profile/service initialization.
 *
 * @param   None.
 *
 * @return  None.
 */
static void ProjectZero_init(void)
{
  // ******************************************************************
  // NO STACK API CALLS CAN OCCUR BEFORE THIS CALL TO ICall_registerApp
  // ******************************************************************
  // Register the current thread as an ICall dispatcher application
  // so that the application can send and receive messages via ICall to Stack.
  ICall_registerApp(&selfEntity, &syncEvent);

  Log_info0("Initializing the user task, hardware, BLE stack and services.");

  // Open display. By default this is disabled via the predefined symbol Display_DISABLE_ALL.
  dispHandle = Display_open(Display_Type_LCD, NULL);

  // Initialize queue for application messages.
  // Note: Used to transfer control to application thread from e.g. interrupts.
  Queue_construct(&applicationMsgQ, NULL);
  hApplicationMsgQ = Queue_handle(&applicationMsgQ);

  // ******************************************************************
  // Hardware initialization
  // ******************************************************************
  ledPinHandle = PIN_open(&ledPinState, ledPinTable);
  if(!ledPinHandle)
  {
    Log_error0("Error initializing board LED pins");
    Task_exit();
  }

  // ******************************************************************
  // BLE Stack initialization
  // ******************************************************************

  // Setup the GAP Peripheral Role Profile
  uint8_t initialAdvertEnable = TRUE;  // Advertise on power-up

  // By setting this to zero, the device will go into the waiting state after
  // being discoverable. Otherwise wait this long [ms] before advertising again.
  uint16_t advertOffTime = 0; // miliseconds

  // Set advertisement enabled.
  GAPRole_SetParameter(GAPROLE_ADVERT_ENABLED, sizeof(uint8_t),
                       &initialAdvertEnable);

  // Configure the wait-time before restarting advertisement automatically
  GAPRole_SetParameter(GAPROLE_ADVERT_OFF_TIME, sizeof(uint16_t),
                       &advertOffTime);

  // Initialize Scan Response data
  GAPRole_SetParameter(GAPROLE_SCAN_RSP_DATA, sizeof(scanRspData), scanRspData);

  // Initialize Advertisement data
  GAPRole_SetParameter(GAPROLE_ADVERT_DATA, sizeof(advertData), advertData);

  Log_info1("Name in advertData array: \x1b[33m%s\x1b[0m",
            (IArg)Util_getLocalNameStr(advertData));

  // Set advertising interval
  uint16_t advInt = DEFAULT_ADVERTISING_INTERVAL;

  GAP_SetParamValue(TGAP_LIM_DISC_ADV_INT_MIN, advInt);
  GAP_SetParamValue(TGAP_LIM_DISC_ADV_INT_MAX, advInt);
  GAP_SetParamValue(TGAP_GEN_DISC_ADV_INT_MIN, advInt);
  GAP_SetParamValue(TGAP_GEN_DISC_ADV_INT_MAX, advInt);

  // Set duration of advertisement before stopping in Limited adv mode.
  GAP_SetParamValue(TGAP_LIM_ADV_TIMEOUT, 30); // Seconds

  // ******************************************************************
  // BLE Bond Manager initialization
  // ******************************************************************
  uint32_t passkey = DEFAULT_PASSCODE;
  uint8_t pairMode = GAPBOND_PAIRING_MODE_WAIT_FOR_REQ;
  uint8_t mitm = TRUE;
  uint8_t ioCap = GAPBOND_IO_CAP_DISPLAY_ONLY;
  uint8_t bonding = TRUE;

  GAPBondMgr_SetParameter(GAPBOND_DEFAULT_PASSCODE, sizeof(uint32_t),
                          &passkey);
  GAPBondMgr_SetParameter(GAPBOND_PAIRING_MODE, sizeof(uint8_t), &pairMode);
  GAPBondMgr_SetParameter(GAPBOND_MITM_PROTECTION, sizeof(uint8_t), &mitm);
  GAPBondMgr_SetParameter(GAPBOND_IO_CAPABILITIES, sizeof(uint8_t), &ioCap);
  GAPBondMgr_SetParameter(GAPBOND_BONDING_ENABLED, sizeof(uint8_t), &bonding);

  // ******************************************************************
  // BLE Service initialization
  // ******************************************************************

  // Add services to GATT server
  GGS_AddService(GATT_ALL_SERVICES);           // GAP
  GATTServApp_AddService(GATT_ALL_SERVICES);   // GATT attributes
  DevInfo_AddService();                        // Device Information Service

  // Set the device name characteristic in the GAP Profile
  GGS_SetParameter(GGS_DEVICE_NAME_ATT, GAP_DEVICE_NAME_LEN, attDeviceName);

// Add services to GATT server and give ID of this task for Indication acks.
  Vogatt_AddService( selfEntity );

  // Register callbacks with the generated services that
  // can generate events (writes received) to the application
  Vogatt_RegisterAppCBs( &user_VoGATTCBs );
  // Placeholder variable for characteristic intialization
  uint8_t someVal[20] = {0};

  // Initalization of characteristics in VoGATT that can provide data
  // to a peer device over the air.
  Vogatt_SetParameter(V_STREAM_START_ID, V_STREAM_START_LEN, &someVal);
  Vogatt_SetParameter(V_STREAM_OUTPUT_ID, V_STREAM_OUTPUT_LEN, &someVal);



  // Start the stack in Peripheral mode.
  VOID GAPRole_StartDevice(&user_gapRoleCBs);

  // Start Bond Manager
  VOID GAPBondMgr_Register(&user_bondMgrCBs);

  // Register with GAP for HCI/Host messages
  GAP_RegisterForMsgs(selfEntity);

  // Register for GATT local events and ATT Responses pending for transmission
  GATT_RegisterForMsgs(selfEntity);

  voice_hdl_init();

  HCI_EXT_SetTxPowerCmd(HCI_EXT_TX_POWER_5_DBM);//HCI_EXT_TX_POWER_MINUS_21_DBM HCI_EXT_TX_POWER_5_DBM
}


/*
 * @brief   Application task entry point.
 *
 *          Invoked by TI-RTOS when BIOS_start is called. Calls an init function
 *          and enters an infinite loop waiting for messages.
 *
 *          Messages can be either directly from the BLE stack or from user code
 *          like Hardware Interrupt (Hwi) or a callback function.
 *
 *          The reason for sending messages to this task from e.g. Hwi's is that
 *          some RTOS and Stack APIs are not available in callbacks and so the
 *          actions that may need to be taken is dispatched to this Task.
 *
 * @param   a0, a1 - not used.
 *
 * @return  None.
 */
static void ProjectZero_taskFxn(UArg a0, UArg a1)
{
  // Initialize application
  ProjectZero_init();

  // Application main loop
  for (;;)
  {
    uint32_t events;

    // Waits for an event to be posted associated with the calling thread.
    // Note that an event associated with a thread is posted when a
    // message is queued to the message receive queue of the thread
    events = Event_pend(syncEvent, Event_Id_NONE, PRZ_ALL_EVENTS,
                        ICALL_TIMEOUT_FOREVER);

    if (events)
    {
      ICall_EntityID dest;
      ICall_ServiceEnum src;
      ICall_HciExtEvt *pMsg = NULL;

      // Check if we got a signal because of a stack message
      if (ICall_fetchServiceMsg(&src, &dest,
                                (void **)&pMsg) == ICALL_ERRNO_SUCCESS)
      {
        uint8 safeToDealloc = TRUE;

        if ((src == ICALL_SERVICE_CLASS_BLE) && (dest == selfEntity))
        {
          ICall_Stack_Event *pEvt = (ICall_Stack_Event *)pMsg;

          // Check for event flags received (event signature 0xffff)
          if (pEvt->signature == 0xffff)
          {
            // Event received when a connection event is completed
            if (pEvt->event_flag & PRZ_CONN_EVT_END_EVT)
            {
              // Try to retransmit pending ATT Response (if any)
              ProjectZero_sendAttRsp();
            }
          }
          else // It's a message from the stack and not an event.
          {
            // Process inter-task message
            safeToDealloc = ProjectZero_processStackMsg((ICall_Hdr *)pMsg);
          }
        }

        if (pMsg && safeToDealloc)
        {
          ICall_freeMsg(pMsg);
        }
      }

      // Process messages sent from another task or another context.
      while (!Queue_empty(hApplicationMsgQ))
      {
        app_msg_t *pMsg = Queue_dequeue(hApplicationMsgQ);

        // Process application-layer message probably sent from ourselves.
        user_processApplicationMessage(pMsg);

        // Free the received message.
        ICall_free(pMsg);
      }

    }
  }
}


#ifdef SINUS_GEN
    #define DATA_SIZE I2S_SAMP_PER_FRAME
    static         int16_t data[DATA_SIZE];

#endif
/*
 * @brief   Handle application messages
 *
 *          These are messages not from the BLE stack, but from the
 *          application itself.
 *
 *          For example, in a Software Interrupt (Swi) it is not possible to
 *          call any BLE APIs, so instead the Swi function must send a message
 *          to the application Task for processing in Task context.
 *
 * @param   pMsg  Pointer to the message of type app_msg_t.
 *
 * @return  None.
 */
static void user_processApplicationMessage(app_msg_t *pMsg)
{
        char_data_t *pCharData = (char_data_t *)pMsg->pdu;
        int16_t raw_data_send[BUFFERSIZE / 4];

  switch (pMsg->type)
  {
        case APP_MSG_SERVICE_WRITE: /* Message about received value write */
            /* Call different handler per service */
            switch(pCharData->svcUUID) {
                case VOGATT_SERV_UUID:
                  user_Vogatt_ValueChangeHandler(pCharData);
                break;
            }
        break;

        case APP_MSG_SERVICE_CFG: /* Message about received CCCD write */
            /* Call different handler per service */
            switch(pCharData->svcUUID) {
                case VOGATT_SERV_UUID:
                    user_Vogatt_CfgChangeHandler(pCharData);
                break;
            }
        break;

        case APP_MSG_UPDATE_CHARVAL: /* Message to self from to update a value */
            user_updateCharVal(pCharData);
        break;


        case APP_MSG_GAP_STATE_CHANGE: /* Message that GAP state changed  */
            user_processGapStateChangeEvt( *(gaprole_States_t *)pMsg->pdu );
        break;

        case APP_MSG_SEND_PASSCODE: /* Message about pairing PIN request */
        {
            passcode_req_t *pReq = (passcode_req_t *)pMsg->pdu;
            Log_info2("BondMgr Requested passcode. We are %s passcode %06d",
              (IArg)(pReq->uiInputs?"Sending":"Displaying"),
              DEFAULT_PASSCODE);
            // Send passcode response.
            GAPBondMgr_PasscodeRsp(pReq->connHandle, SUCCESS, DEFAULT_PASSCODE);
        }
        break;

        case APP_MSG_SEND_VOICE_SAMP:
            //decoder_adpcm.previndex = 0;
            //decoder_adpcm.prevsample = 0;
            ADPCMDecoderBuf(pMsg->pdu, raw_data_send, &decoder_adpcm);
#ifdef BT_PACKET_DEBUG

            rx_data[rx_counter++] = pMsg->pdu[0];
            if(rx_counter == TEST_SIZE)
            { uint8_t temp =rx_data[0];
                rx_counter = 0;
                for(uint8_t i=0;i<TEST_SIZE-1;i++)
                    if((rx_data[i+1]) !=(uint8_t)(rx_data[i]+1)){
                        number_of_losts++;
                        packets_lost+= abs(rx_data[i+1]-rx_data[i]+1);
                        i++;
                    }
            }
#endif

#ifdef SINUS_GEN
            for(int16_t i = 0; i<DATA_SIZE;i++){
                 raw_data_send[i] = data[i];
            }
#endif
            bool gotBuffer = I2SCC26XX_requestBuffer(i2sHandle, &bufferRequest);
            if (gotBuffer)
            {
                memcpy(bufferRequest.bufferOut, raw_data_send, sizeof(raw_data_send));
                bufferRelease.bufferHandleOut = bufferRequest.bufferHandleOut;
                bufferRelease.bufferHandleIn = NULL;
                I2SCC26XX_releaseBuffer(i2sHandle, &bufferRelease);
                gotBuffer = 0;
            }
            /*
            for(uint32_t i = 0; i < 80; i++)
                raw_data_send[i] = pMsg->pdu[0] * 255;
            */
            //Mailbox_post(mailbox, raw_data_send, BIOS_NO_WAIT);
        break;

        case APP_MSG_GET_VOICE_SAMP:

            pdm_samp_hdl();

            if(red_counter++ > LED_COUNTER)
            {
                PIN_setOutputValue(ledPinHandle, Board_RLED, !PIN_getOutputValue(Board_RLED));
                red_counter = 0;
            }
        break;
  }
}


/******************************************************************************
 *****************************************************************************
 *
 *  Handlers of system/application events deferred to the user Task context.
 *  Invoked from the application Task function above.
 *
 *  Further down you can find the callback handler section containing the
 *  functions that defer their actions via messages to the application task.
 *
 ****************************************************************************
 *****************************************************************************/


/*
 * @brief   Process a pending GAP Role state change event.
 *
 * @param   newState - new state
 *
 * @return  None.
 */
static void user_processGapStateChangeEvt(gaprole_States_t newState)
{
  switch ( newState )
  {
    case GAPROLE_STARTED:
      {
        uint8_t ownAddress[B_ADDR_LEN];
        uint8_t systemId[DEVINFO_SYSTEM_ID_LEN];

        GAPRole_GetParameter(GAPROLE_BD_ADDR, ownAddress);

        // use 6 bytes of device address for 8 bytes of system ID value
        systemId[0] = ownAddress[0];
        systemId[1] = ownAddress[1];
        systemId[2] = ownAddress[2];

        // set middle bytes to zero
        systemId[4] = 0x00;
        systemId[3] = 0x00;

        // shift three bytes up
        systemId[7] = ownAddress[5];
        systemId[6] = ownAddress[4];
        systemId[5] = ownAddress[3];

        DevInfo_SetParameter(DEVINFO_SYSTEM_ID, DEVINFO_SYSTEM_ID_LEN, systemId);

        // Display device address
        char *cstr_ownAddress = Util_convertBdAddr2Str(ownAddress);
        Log_info1("GAP is started. Our address: \x1b[32m%s\x1b[0m", (IArg)cstr_ownAddress);
      }
      break;

    case GAPROLE_ADVERTISING:
      Log_info0("Advertising");
      break;

    case GAPROLE_CONNECTED:
      {
        uint8_t peerAddress[B_ADDR_LEN];

        GAPRole_GetParameter(GAPROLE_CONN_BD_ADDR, peerAddress);

        char *cstr_peerAddress = Util_convertBdAddr2Str(peerAddress);
        Log_info1("Connected. Peer address: \x1b[32m%s\x1b[0m", (IArg)cstr_peerAddress);
       }
      break;

    case GAPROLE_CONNECTED_ADV:
      Log_info0("Connected and advertising");
      break;

    case GAPROLE_WAITING:

      // Turn off periodic clocks for ind/noti demo
      Clock_stop((Clock_Handle)&v_STREAM_OUTPUT_clock);
      stop_voice_handle();
      Log_info0("Disconnected / Idle");
      break;

    case GAPROLE_WAITING_AFTER_TIMEOUT:

      // Turn off periodic clocks for ind/noti demo
      Clock_stop((Clock_Handle)&v_STREAM_OUTPUT_clock);
      //stop_voice_handle();
      Log_info0("Connection timed out");
      break;

    case GAPROLE_ERROR:
      Log_info0("Error");
      break;

    default:
      break;
  }
}




/*
 * @brief   Handle a write request sent from a peer device.
 *
 *          Invoked by the Task based on a message received from a callback.
 *
 *          When we get here, the request has already been accepted by the
 *          service and is valid from a BLE protocol perspective as well as
 *          having the correct length as defined in the service implementation.
 *
 * @param   pCharData  pointer to malloc'd char write data
 *
 * @return  None.
 */
void user_Vogatt_ValueChangeHandler(char_data_t *pCharData)
{
  static uint8_t pretty_data_holder[16]; // 5 bytes as hex string "AA:BB:CC:DD:EE"
  Util_convertArrayToHexString(pCharData->data, pCharData->dataLen,
                               pretty_data_holder, sizeof(pretty_data_holder));

  switch (pCharData->paramID)
  {
    case V_STREAM_START_ID:
      Log_info3("Value Change msg: %s %s: %s",
                (IArg)"VoGATT",
                (IArg)"STREAM_START",
                (IArg)pretty_data_holder);

      // Do something useful with pCharData->data here

      // -------------------------
      break;

    case V_STREAM_INPUT_ID:  //rx data here!!!
      Log_info3("Value Change msg: %s %s: %s",
                (IArg)"VoGATT",
                (IArg)"STREAM_INPUT",
                (IArg)pretty_data_holder);

      // Do something useful with pCharData->data here

          if(green_counter++ > LED_COUNTER)
          {
              PIN_setOutputValue(ledPinHandle, Board_GLED, !PIN_getOutputValue(Board_GLED));
              green_counter = 0;
          }
          user_enqueueRawAppMsg(APP_MSG_SEND_VOICE_SAMP, pCharData->data, 20);

      // -------------------------
      break;

  default:
    return;
  }
}

/*
 * @brief   Handle a CCCD (configuration change) write received from a peer
 *          device. This tells us whether the peer device wants us to send
 *          Notifications or Indications.
 *
 * @param   pCharData  pointer to malloc'd char write data
 *
 * @return  None.
 */
void user_Vogatt_CfgChangeHandler(char_data_t *pCharData)
{
  // Cast received data to uint16, as that's the format for CCCD writes.
  uint16_t configValue = *(uint16_t *)pCharData->data;
  char *configValString;

  // Determine what to tell the user
  switch(configValue)
  {
  case GATT_CFG_NO_OPERATION:
    configValString = "Noti/Ind disabled";
    break;
  case GATT_CLIENT_CFG_NOTIFY:
    configValString = "Notifications enabled";
    break;
  case GATT_CLIENT_CFG_INDICATE:
    configValString = "Indications enabled";
    break;
  }

  /* Enable notification */
  switch (pCharData->paramID)
  {
    case V_STREAM_OUTPUT_ID:
      Log_info3("CCCD Change msg: %s %s: %s",
                (IArg)"VoGATT",
                (IArg)"STREAM_OUTPUT",
                (IArg)configValString);
      // -------------------------
      // Do something useful with configValue here. It tells you whether someone
      // wants to know the state of this characteristic.
      // ... In the generated example we turn periodic clocks on/off
      if (configValue) // 0x0001 and 0x0002 both indicate turned on.
      {
        GAPRole_SendUpdateParam(8, 8, 0, 100, GAPROLE_TERMINATE_LINK);
        PIN_setOutputValue(ledPinHandle, Board_RLED, 1);
        start_voice_handle();
      }
      else
      {
        PIN_setOutputValue(ledPinHandle, Board_RLED, 0);
        stop_voice_handle();
      }
      break;

  default:
    return;
  }
}


/*
 * @brief   Process an incoming BLE stack message.
 *
 *          This could be a GATT message from a peer device like acknowledgement
 *          of an Indication we sent, or it could be a response from the stack
 *          to an HCI message that the user application sent.
 *
 * @param   pMsg - message to process
 *
 * @return  TRUE if safe to deallocate incoming message, FALSE otherwise.
 */
static uint8_t ProjectZero_processStackMsg(ICall_Hdr *pMsg)
{
  uint8_t safeToDealloc = TRUE;

  switch (pMsg->event)
  {
    case GATT_MSG_EVENT:
      // Process GATT message
      safeToDealloc = ProjectZero_processGATTMsg((gattMsgEvent_t *)pMsg);
      break;

    case HCI_GAP_EVENT_EVENT:
      {
        // Process HCI message
        switch(pMsg->status)
        {
          case HCI_COMMAND_COMPLETE_EVENT_CODE:
            // Process HCI Command Complete Event
            Log_info0("HCI Command Complete Event received");
            break;

          default:
            break;
        }
      }
      break;

    default:
      // do nothing
      break;
  }

  return (safeToDealloc);
}


/*
 * @brief   Process GATT messages and events.
 *
 * @return  TRUE if safe to deallocate incoming message, FALSE otherwise.
 */
static uint8_t ProjectZero_processGATTMsg(gattMsgEvent_t *pMsg)
{
  // See if GATT server was unable to transmit an ATT response
  if (pMsg->hdr.status == blePending)
  {
    Log_warning1("Outgoing RF FIFO full. Re-schedule transmission of msg with opcode 0x%02x",
      pMsg->method);

    // No HCI buffer was available. Let's try to retransmit the response
    // on the next connection event.
    if (HCI_EXT_ConnEventNoticeCmd(pMsg->connHandle, selfEntity,
                                   PRZ_CONN_EVT_END_EVT) == SUCCESS)
    {
      // First free any pending response
      ProjectZero_freeAttRsp(FAILURE);

      // Hold on to the response message for retransmission
      pAttRsp = pMsg;

      // Don't free the response message yet
      return (FALSE);
    }
  }
  else if (pMsg->method == ATT_FLOW_CTRL_VIOLATED_EVENT)
  {
    // ATT request-response or indication-confirmation flow control is
    // violated. All subsequent ATT requests or indications will be dropped.
    // The app is informed in case it wants to drop the connection.

    // Log the opcode of the message that caused the violation.
    Log_error1("Flow control violated. Opcode of offending ATT msg: 0x%02x",
      pMsg->msg.flowCtrlEvt.opcode);
  }
  else if (pMsg->method == ATT_MTU_UPDATED_EVENT)
  {
    // MTU size updated
    Log_info1("MTU Size change: %d bytes", pMsg->msg.mtuEvt.MTU);
  }
  else
  {
    // Got an expected GATT message from a peer.
    Log_info1("Recevied GATT Message. Opcode: 0x%02x", pMsg->method);
  }

  // Free message payload. Needed only for ATT Protocol messages
  GATT_bm_free(&pMsg->msg, pMsg->method);

  // It's safe to free the incoming message
  return (TRUE);
}




/*
 *  Application error handling functions
 *****************************************************************************/

/*
 * @brief   Send a pending ATT response message.
 *
 *          The message is one that the stack was trying to send based on a
 *          peer request, but the response couldn't be sent because the
 *          user application had filled the TX queue with other data.
 *
 * @param   none
 *
 * @return  none
 */
static void ProjectZero_sendAttRsp(void)
{
  // See if there's a pending ATT Response to be transmitted
  if (pAttRsp != NULL)
  {
    uint8_t status;

    // Increment retransmission count
    rspTxRetry++;

    // Try to retransmit ATT response till either we're successful or
    // the ATT Client times out (after 30s) and drops the connection.
    status = GATT_SendRsp(pAttRsp->connHandle, pAttRsp->method, &(pAttRsp->msg));
    if ((status != blePending) && (status != MSG_BUFFER_NOT_AVAIL))
    {
      // Disable connection event end notice
      HCI_EXT_ConnEventNoticeCmd(pAttRsp->connHandle, selfEntity, 0);

      // We're done with the response message
      ProjectZero_freeAttRsp(status);
    }
    else
    {
      // Continue retrying
      Log_warning2("Retrying message with opcode 0x%02x. Attempt %d",
        pAttRsp->method, rspTxRetry);
    }
  }
}

/*
 * @brief   Free ATT response message.
 *
 * @param   status - response transmit status
 *
 * @return  none
 */
static void ProjectZero_freeAttRsp(uint8_t status)
{
  // See if there's a pending ATT response message
  if (pAttRsp != NULL)
  {
    // See if the response was sent out successfully
    if (status == SUCCESS)
    {
      Log_info2("Sent message with opcode 0x%02x. Attempt %d",
        pAttRsp->method, rspTxRetry);
    }
    else
    {
      Log_error2("Gave up message with opcode 0x%02x. Status: %d",
        pAttRsp->method, status);

      // Free response payload
      GATT_bm_free(&pAttRsp->msg, pAttRsp->method);
    }

    // Free response message
    ICall_freeMsg(pAttRsp);

    // Reset our globals
    pAttRsp = NULL;
    rspTxRetry = 0;
  }
}


/******************************************************************************
 *****************************************************************************
 *
 *  Handlers of direct system callbacks.
 *
 *  Typically enqueue the information or request as a message for the
 *  application Task for handling.
 *
 ****************************************************************************
 *****************************************************************************/


/*
 *  Callbacks from the Stack Task context (GAP or Service changes)
 *****************************************************************************/

/**
 * Callback from GAP Role indicating a role state change.
 */
static void user_gapStateChangeCB(gaprole_States_t newState)
{
  Log_info1("(CB) GAP State change: %d, Sending msg to app.", (IArg)newState);
  user_enqueueRawAppMsg( APP_MSG_GAP_STATE_CHANGE, (uint8_t *)&newState, sizeof(newState) );
}

/*
 * @brief   Passcode callback.
 *
 * @param   connHandle - connection handle
 * @param   uiInputs   - input passcode?
 * @param   uiOutputs  - display passcode?
 * @param   numComparison - numeric comparison value
 *
 * @return  none
 */
static void user_gapBondMgr_passcodeCB(uint8_t *deviceAddr, uint16_t connHandle,
                                       uint8_t uiInputs, uint8_t uiOutputs, uint32 numComparison)
{
  passcode_req_t req =
  {
    .connHandle = connHandle,
    .uiInputs = uiInputs,
    .uiOutputs = uiOutputs,
    .numComparison = numComparison
  };

  // Defer handling of the passcode request to the application, in case
  // user input is required, and because a BLE API must be used from Task.
  user_enqueueRawAppMsg(APP_MSG_SEND_PASSCODE, (uint8_t *)&req, sizeof(req));
}

/*
 * @brief   Pairing state callback.
 *
 * @param   connHandle - connection handle
 * @param   state      - pairing state
 * @param   status     - pairing status
 *
 * @return  none
 */
static void user_gapBondMgr_pairStateCB(uint16_t connHandle, uint8_t state,
                                        uint8_t status)
{
  if (state == GAPBOND_PAIRING_STATE_STARTED)
  {
    Log_info0("Pairing started");
  }
  else if (state == GAPBOND_PAIRING_STATE_COMPLETE)
  {
    if (status == SUCCESS)
    {
      Log_info0("Pairing completed successfully.");
    }
    else
    {
      Log_error1("Pairing failed. Error: %02x", status);
    }
  }
  else if (state == GAPBOND_PAIRING_STATE_BONDED)
  {
    if (status == SUCCESS)
    {
     Log_info0("Re-established pairing from stored bond info.");
    }
  }
}

/**
 * Callback handler for characteristic value changes in services.
 */
static void user_service_ValueChangeCB( uint16_t connHandle, uint16_t svcUuid,
                                        uint8_t paramID, uint8_t *pValue,
                                        uint16_t len )
{
  // See the service header file to compare paramID with characteristic.
  Log_info2("(CB) Characteristic value change: svc(0x%04x) paramID(%d). "
            "Sending msg to app.", (IArg)svcUuid, (IArg)paramID);
  user_enqueueCharDataMsg(APP_MSG_SERVICE_WRITE, connHandle, svcUuid, paramID,
                          pValue, len);
}

/**
 * Callback handler for characteristic configuration changes in services.
 */
static void user_service_CfgChangeCB( uint16_t connHandle, uint16_t svcUuid,
                                      uint8_t paramID, uint8_t *pValue,
                                      uint16_t len )
{
  Log_info2("(CB) Char config change: svc(0x%04x) paramID(%d). "
            "Sending msg to app.", (IArg)svcUuid, (IArg)paramID);
  user_enqueueCharDataMsg(APP_MSG_SERVICE_CFG, connHandle, svcUuid,
                          paramID, pValue, len);
}

/*
 *  Callbacks from Swi-context
 *****************************************************************************/

/*
 *  Callbacks from Hwi-context
 *****************************************************************************/


/******************************************************************************
 *****************************************************************************
 *
 *  Utility functions
 *
 ****************************************************************************
 *****************************************************************************/

/*
 * @brief  Generic message constructor for characteristic data.
 *
 *         Sends a message to the application for handling in Task context where
 *         the message payload is a char_data_t struct.
 *
 *         From service callbacks the appMsgType is APP_MSG_SERVICE_WRITE or
 *         APP_MSG_SERVICE_CFG, and functions running in another context than
 *         the Task itself, can set the type to APP_MSG_UPDATE_CHARVAL to
 *         make the user Task loop invoke user_updateCharVal function for them.
 *
 * @param  appMsgType    Enumerated type of message being sent.
 * @param  connHandle    GAP Connection handle of the relevant connection
 * @param  serviceUUID   16-bit part of the relevant service UUID
 * @param  paramID       Index of the characteristic in the service
 * @oaram  *pValue       Pointer to characteristic value
 * @param  len           Length of characteristic data
 */
static void user_enqueueCharDataMsg( app_msg_types_t appMsgType,
                                     uint16_t connHandle,
                                     uint16_t serviceUUID, uint8_t paramID,
                                     uint8_t *pValue, uint16_t len )
{
  // Called in Stack's Task context, so can't do processing here.
  // Send message to application message queue about received data.
  uint16_t readLen = len; // How much data was written to the attribute

  // Allocate memory for the message.
  // Note: The pCharData message doesn't have to contain the data itself, as
  //       that's stored in a variable in the service implementation.
  //
  //       However, to prevent data loss if a new value is received before the
  //       service's container is read out via the GetParameter API is called,
  //       we copy the characteristic's data now.
  app_msg_t *pMsg = ICall_malloc( sizeof(app_msg_t) + sizeof(char_data_t) +
                                  readLen );

  if (pMsg != NULL)
  {
    pMsg->type = appMsgType;

    char_data_t *pCharData = (char_data_t *)pMsg->pdu;
    pCharData->svcUUID = serviceUUID; // Use 16-bit part of UUID.
    pCharData->paramID = paramID;
    // Copy data from service now.
    memcpy(pCharData->data, pValue, readLen);
    // Update pCharData with how much data we received.
    pCharData->dataLen = readLen;
    // Enqueue the message using pointer to queue node element.
    Queue_enqueue(hApplicationMsgQ, &pMsg->_elem);
  // Let application know there's a message.
  Event_post(syncEvent, PRZ_APP_MSG_EVT);
  }
}

/*
 * @brief  Generic message constructor for application messages.
 *
 *         Sends a message to the application for handling in Task context.
 *
 * @param  appMsgType    Enumerated type of message being sent.
 * @oaram  *pValue       Pointer to characteristic value
 * @param  len           Length of characteristic data
 */
static void user_enqueueRawAppMsg(app_msg_types_t appMsgType, uint8_t *pData,
                                  uint16_t len)
{
  // Allocate memory for the message.
  app_msg_t *pMsg = ICall_malloc( sizeof(app_msg_t) + len );

  if (pMsg != NULL)
  {
    pMsg->type = appMsgType;

    // Copy data into message
    memcpy(pMsg->pdu, pData, len);

    // Enqueue the message using pointer to queue node element.

    Queue_enqueue(hApplicationMsgQ, &pMsg->_elem);
//    // Let application know there's a message.
    Event_post(syncEvent, PRZ_APP_MSG_EVT);
  }
}


/*
 * @brief  Convenience function for updating characteristic data via char_data_t
 *         structured message.
 *
 * @note   Must run in Task context in case BLE Stack APIs are invoked.
 *
 * @param  *pCharData  Pointer to struct with value to update.
 */
static void user_updateCharVal(char_data_t *pCharData)
{
  switch(pCharData->svcUUID)
  {
    case VOGATT_SERV_UUID:
      Vogatt_SetParameter( pCharData->paramID,
              pCharData->dataLen, pCharData->data );
    break;

  }
}

/*
 * @brief   Convert {0x01, 0x02} to "01:02"
 *
 * @param   src - source byte-array
 * @param   src_len - length of array
 * @param   dst - destination string-array
 * @param   dst_len - length of array
 *
 * @return  array as string
 */
static char *Util_convertArrayToHexString(uint8_t const *src, uint8_t src_len,
                                          uint8_t *dst, uint8_t dst_len)
{
  char        hex[] = "0123456789ABCDEF";
  uint8_t     *pStr = dst;
  uint8_t     avail = dst_len-1;

  memset(dst, 0, avail);

  while (src_len && avail > 3)
  {
    if (avail < dst_len-1) { *pStr++ = ':'; avail -= 1; };
    *pStr++ = hex[*src >> 4];
    *pStr++ = hex[*src++ & 0x0F];
    avail -= 2;
    src_len--;
  }

  if (src_len && avail)
    *pStr++ = ':'; // Indicate not all data fit on line.

  return (char *)dst;
}

/*
 * @brief   Extract the LOCALNAME from Scan/AdvData
 *
 * @param   data - Pointer to the advertisement or scan response data
 *
 * @return  Pointer to null-terminated string with the adv local name.
 */
static char *Util_getLocalNameStr(const uint8_t *data) {
  uint8_t nuggetLen = 0;
  uint8_t nuggetType = 0;
  uint8_t advIdx = 0;

  static char localNameStr[32] = { 0 };
  memset(localNameStr, 0, sizeof(localNameStr));

  for (advIdx = 0; advIdx < 32;) {
    nuggetLen = data[advIdx++];
    nuggetType = data[advIdx];
    if ( (nuggetType == GAP_ADTYPE_LOCAL_NAME_COMPLETE ||
          nuggetType == GAP_ADTYPE_LOCAL_NAME_SHORT) && nuggetLen < 31) {
      memcpy(localNameStr, &data[advIdx + 1], nuggetLen - 1);
      break;
    } else {
      advIdx += nuggetLen;
    }
  }

  return localNameStr;
}

static void *SA_audioMalloc(uint_least16_t size)
{
    Error_Block eb;
    Error_init(&eb);
    return Memory_alloc(NULL, size, 0, &eb);
}

static void SA_audioFree(void *msg, size_t size)
{
    Memory_free(NULL, msg, size);
}


/* Functions for handle tx/rx packets of voice samples */
static void voice_hdl_init(void)
{
    mailbox = Mailbox_create(BUFFERSIZE / 2, 2, NULL, NULL);
    if (mailbox == NULL) {
        while (1);
    }

    GPTimerCC26XX_Params_init(&tim_params);
    tim_params.width = GPT_CONFIG_16BIT;
    tim_params.mode = GPT_MODE_PERIODIC_UP;
    tim_params.debugStallMode = GPTimerCC26XX_DEBUG_STALL_OFF;
    tim_hdl = GPTimerCC26XX_open(Board_GPTIMER2B, &tim_params);
    if (tim_hdl == NULL) {
        while (1);
    }
    GPTimerCC26XX_Value loadVal = 479999/*5999*/;
    GPTimerCC26XX_setLoadValue(tim_hdl, loadVal);
    GPTimerCC26XX_registerInterrupt(tim_hdl, timer_callback, GPT_INT_TIMEOUT);
#ifdef SINUS_GEN
            for(int16_t i = 0; i<DATA_SIZE;i++){
                data[i]=(int16_t)(sin(i*M_PI/180.0*4.55)*8192.0);
            }
#endif
//    PWM_init();
//
//    PWM_Params_init(&pwm_params);
//    pwm_params.dutyUnits = PWM_DUTY_FRACTION;
//    pwm_params.dutyValue = 0;
//    pwm_params.periodUnits = PWM_PERIOD_HZ;
//    pwm_params.periodValue = PWM_PERIOD;
//    pwm_hdl = PWM_open(CC2640R2_LAUNCHXL_PWM2, &pwm_params);
//    if (pwm_hdl == NULL) {
//        while (1);
//    }

    CryptoCC26XX_init();

    crypto_handle = CryptoCC26XX_open(Board_CRYPTO0, false, NULL);
    if (!crypto_handle) {
        while(1);
    }

    key_index = CryptoCC26XX_allocateKey(crypto_handle, CRYPTOCC26XX_KEY_3, (const uint32_t *)key);

    if (key_index == CRYPTOCC26XX_STATUS_ERROR) {
       while(1);
    }

    /*
    PDMCC26XX_init(pdmHandle);

    // Set up parameters for PDM streaming without compression
    PDMCC26XX_Params_init(&pdmParams);
    pdmParams.callbackFxn = bufRdy_callback;
    pdmParams.micPowerActiveHigh = true;
    pdmParams.applyCompression = false;
    pdmParams.retBufSizeInBytes = returnBufferSize + 4;
    pdmParams.mallocFxn = (PDMCC26XX_MallocFxn) SA_audioMalloc;
    pdmParams.freeFxn = SA_audioFree;
    pdmParams.useDefaultFilter = true;
    pdmParams.decimationFilter = NULL;
    pdmParams.micGain = PDMCC26XX_GAIN_N6;

    // Try to open the PDM driver
    pdmHandle = PDMCC26XX_open(&pdmParams);
    if(!pdmHandle){
        while(1);
    }
    */
    /* ADC init */
    ADCBuf_init();

    ADCBuf_Params_init(&adc_params);
    adc_params.callbackFxn = adc_callback;
    adc_params.recurrenceMode = ADCBuf_RECURRENCE_MODE_CONTINUOUS;
    adc_params.returnMode = ADCBuf_RETURN_MODE_CALLBACK;
    adc_params.samplingFrequency = SAMPFREQ;

    adc_hdl = ADCBuf_open(Board_ADCBUF0, &adc_params);
//


    I2SCC26XX_init(i2sHandle);
    I2SCC26XX_Handle i2sHandleTmp = NULL;
    AudioDuplex_disableCache();

    i2sContMgtBuffer = (uint8_t *)(I2S_MEM_BASE + I2S_BUF + 1);
    audio_decoded = (int16_t *)I2S_MEM_BASE;
    // Setup I2S Params
    i2sParams.blockSize              = I2S_SAMP_PER_FRAME;
    i2sParams.pvContBuffer           = (void *) audio_decoded;
    i2sParams.pvContMgtBuffer        = (void *) i2sContMgtBuffer;
    i2sParams.ui32conMgtBufTotalSize =  I2S_BLOCK_OVERHEAD_IN_BYTES *  \
                                        I2SCC26XX_QUEUE_SIZE\
                                        * 2;

    i2sParams.ui32conBufTotalSize    =  sizeof(int16_t) * (I2S_SAMP_PER_FRAME * \
                                        I2SCC26XX_QUEUE_SIZE \
                                        * 2);
    // Reset I2S handle and attempt to open
    i2sHandle = (I2SCC26XX_Handle)&(I2SCC26XX_config);
    i2sHandleTmp = I2SCC26XX_open(i2sHandle, &i2sParams);

    // Try to open the PDM driver
    //pdmHandle = PDMCC26XX_open(&pdmParams);
    if(!i2sHandleTmp){//pdmHandle){
        while(1);
    }

    bufferRequest.buffersRequested = I2SCC26XX_BUFFER_OUT;

    //i2sStreamInProgress = I2SCC26XX_startStream(i2sHandle);
}

//static void bufRdy_callback(PDMCC26XX_Handle handle, PDMCC26XX_StreamNotification *pStreamNotification)
//{
//  PDMCC26XX_Status streamStatus = pStreamNotification->status;
//
//  if (streamStatus == PDMCC26XX_STREAM_BLOCK_READY || streamStatus == PDMCC26XX_STREAM_BLOCK_READY_BUT_PDM_OVERFLOW) {
//      user_enqueueRawAppMsg(APP_MSG_GET_VOICE_SAMP, &pdm_val, 1);// TODO
//  }
//}

void adc_callback(ADCBuf_Handle handle, ADCBuf_Conversion *conversion,
    void *completedADCBuffer, uint32_t completedChannel) {

    int16_t *buf_ptr = (int16_t*)completedADCBuffer;
    /* handle receive data */
    for(uint32_t i = 0 ; i < ADCBUFSIZE; i++)
        adc_data[i] = (buf_ptr[i] - 1550);

    if(stream_on)
        user_enqueueRawAppMsg(APP_MSG_GET_VOICE_SAMP, &pdm_val, 1);
}

static void bufRdy_callback(I2SCC26XX_Handle handle, I2SCC26XX_StreamNotification *pStreamNotification)
{
    I2SCC26XX_Status streamStatus = pStreamNotification->status;

    if (streamStatus == I2SCC26XX_STREAM_BUFFER_READY || streamStatus == I2SCC26XX_STREAM_BUFFER_READY_BUT_NO_AVAILABLE_BUFFERS) {
        //user_enqueueRawAppMsg(APP_MSG_GET_VOICE_SAMP, &i2s_val, 1);
    }
}

static void timer_callback(GPTimerCC26XX_Handle handle, GPTimerCC26XX_IntMask interruptMask)
{
    static Bool ready = FALSE;
    //static uint32_t counter = 0;
    static int16_t raw_data_tmr[BUFFERSIZE / 4];

    tmr_counter++;

    if (!ready) {
        ready = Mailbox_pend(mailbox, raw_data_tmr, BIOS_NO_WAIT);
    }

    if(ready)
    {
        //bufferRequest.buffersRequested = I2SCC26XX_BUFFER_OUT;
        i2s_counter++;
        bool gotBuffer = I2SCC26XX_requestBuffer(i2sHandle, &bufferRequest);
        if (gotBuffer)
        {
            //memset(bufferRequest.bufferOut, &data[0], 96);
            memcpy(bufferRequest.bufferOut, raw_data_tmr, sizeof(raw_data_tmr));
            bufferRelease.bufferHandleOut = bufferRequest.bufferHandleOut;
            bufferRelease.bufferHandleIn = NULL;
            I2SCC26XX_releaseBuffer(i2sHandle, &bufferRelease);
            gotBuffer = 0;
        }
        ready = false;
    }

}

static void start_voice_handle(void)
{
    //gsit_init_state(&encoder);
    //gsit_init_state(&decoder);

    //GPTimerCC26XX_start(tim_hdl);

    // Try to start streaming
    /*
    status_pdm = PDMCC26XX_startStream(pdmHandle);
    if(!status_pdm){
        while(1);
    }
    */


    adc_conversion.arg = NULL;
    adc_conversion.adcChannel = CC2640R2_LAUNCHXL_ADCBUF0CHANNEL7;
    adc_conversion.sampleBuffer = samp_buf1;
    adc_conversion.sampleBufferTwo = samp_buf2;
    adc_conversion.samplesRequestedCount = ADCBUFSIZE;
    if (!adc_hdl){
        while(1);
    }
    /* Start converting. */
    if (ADCBuf_convert(adc_hdl, &adc_conversion, 1) != ADCBuf_STATUS_SUCCESS) {
        while(1);
    }
    /* ADC init end */
//    PWM_setDuty(pwm_hdl, 0);
    //PWM_start(pwm_hdl);
    i2sStreamInProgress = I2SCC26XX_startStream(i2sHandle);
    //HCI_EXT_SetTxPowerCmd(HCI_EXT_TX_POWER_5_DBM);
    stream_on = 1;
}

static void stop_voice_handle(void)
{

    if(stream_on)
    {
        if(!I2SCC26XX_stopStream(i2sHandle)){
           while(1);
        }
        //HCI_EXT_SetTxPowerCmd(HCI_EXT_TX_POWER_0_DBM);
        stream_on = 0;
    }

    ADCBuf_convertCancel(adc_hdl);
    //PWM_stop(pwm_hdl);
    stream_on = 0;
    //GPTimerCC26XX_stop(tim_hdl);
}

static void pdm_samp_hdl(void)
{
    //PDMCC26XX_requestBuffer(pdmHandle, &bufferRequest);
    uint8_t encode_buf[20];
    //uint8_t encrypted[16] = {0};
    //uint8_t decrypted[16] = {0};
    static uint8_t counter = 0;

    //memset(&encode_buf[10], 0, 6);

   // memcpy(buf, adc_data, BUFFERSIZE);
    //memcpy(buf, bufferRequest.buffer->pBuffer, BUFFERSIZE);
    //SA_audioFree(bufferRequest.buffer, returnBufferSize + 4);

    //for(counter = 0; counter < BUFFERSIZE; counter+=4)
   // {
   //     raw_data[counter / 4] = ((int16_t)(buf[counter + 1])) | ((int16_t)(buf[counter]) << 8);
   // }

    //encoder_adpcm.previndex = 0;
    //encoder_adpcm.prevsample = 0;
    //ADPCMEncoderBuf(raw_data, encode_buf, &encoder_adpcm);
    ADPCMEncoderBuf(adc_data, encode_buf, &encoder_adpcm);
    /*
    CryptoCC26XX_Transac_init((CryptoCC26XX_Transaction *) &trans, CRYPTOCC26XX_OP_AES_ECB_ENCRYPT);
    trans.keyIndex         = key_index;
    trans.msgIn            = (uint32_t *)encode_buf;
    trans.msgOut           = (uint32_t *)encrypted;

    crypto_status = CryptoCC26XX_transact(crypto_handle, (CryptoCC26XX_Transaction *) &trans);
    if(crypto_status != CRYPTOCC26XX_STATUS_SUCCESS){
       while(1);
    }

    CryptoCC26XX_Transac_init((CryptoCC26XX_Transaction *) &trans, CRYPTOCC26XX_OP_AES_ECB_DECRYPT);
    trans.keyIndex         = key_index;
    trans.msgIn            = (uint32_t *)encrypted;
    trans.msgOut           = (uint32_t *)decrypted;

    crypto_status = CryptoCC26XX_transact(crypto_handle, (CryptoCC26XX_Transaction *) &trans);
    if(status != CRYPTOCC26XX_STATUS_SUCCESS){
       while(1);
    }
    */
    //SitDecoder(encode_buf, raw_data_send, &decoder);

    //Mailbox_post(mailbox, raw_data_send, BIOS_NO_WAIT);
#ifdef BT_PACKET_DEBUG
    encode_buf[0] = counter;
    counter++;
#endif
    Vogatt_SetParameter(V_STREAM_OUTPUT_ID, 20, encode_buf);

//    if(counter == 32)
//    {
//        counter = 0;
//    }
}

/*********************************************************************
 *********************************************************************/

/*********************************************************************
 * @fn      AudioDuplex_disableCache
 *
 * @brief   Disables the instruction cache and sets power constaints
 *          This prevents the device from sleeping while streaming
 *
 * @param   None.
 *
 * @return  None.
 */
static void AudioDuplex_disableCache()
{
    uint_least16_t hwiKey = Hwi_disable();
    Power_setConstraint(PowerCC26XX_SB_VIMS_CACHE_RETAIN);
    Power_setConstraint(PowerCC26XX_NEED_FLASH_IN_IDLE);
    VIMSModeSafeSet(VIMS_BASE, VIMS_MODE_DISABLED, true);
    Hwi_restore(hwiKey);
}
