/******************************************************************************
 * Filename:       VoGATT.h
 *
 * Description:    This file contains the VoGATT service definitions and
 *                 prototypes.
 *
 *                 Generated by:
 *                 BDS version: 1.1.3139.0
 *                 Plugin:      Texas Instruments BLE SDK GATT Server plugin 1.0.9
 *                 Time:        Fri Sep 15 2017 01:07:25 GMT+07:00
 *

 * Copyright (c) 2015-2017, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *****************************************************************************/

#ifndef _VOGATT_H_
#define _VOGATT_H_

#ifdef __cplusplus
extern "C"
{
#endif

/*********************************************************************
 * INCLUDES
 */
#include <bcomdef.h>

/*********************************************************************
 * CONSTANTS
 */
// Service UUID
#define VOGATT_SERV_UUID 0xB000
#define VOGATT_SERV_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0

// STREAM_START Characteristic defines
#define V_STREAM_START_ID                 0
#define V_STREAM_START_UUID               0xB001
#define V_STREAM_START_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define V_STREAM_START_LEN                20
#define V_STREAM_START_LEN_MIN            20

// STREAM_INPUT Characteristic defines
#define V_STREAM_INPUT_ID                 1
#define V_STREAM_INPUT_UUID               0xB002
#define V_STREAM_INPUT_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define V_STREAM_INPUT_LEN                51
#define V_STREAM_INPUT_LEN_MIN            51
#define V_STREAM_INPUT_SOUND_LEN          40

// STREAM_OUTPUT Characteristic defines
#define V_STREAM_OUTPUT_ID                 2
#define V_STREAM_OUTPUT_UUID               0xB003
#define V_STREAM_OUTPUT_UUID_BASE128(uuid) 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xB0, 0x00, 0x40, 0x51, 0x04, LO_UINT16(uuid), HI_UINT16(uuid), 0x00, 0xF0
#define V_STREAM_OUTPUT_LEN                51
#define V_STREAM_OUTPUT_LEN_MIN            51
#define V_STREAM_OUTPUT_SOUND_LEN          40

#define V_STREAM_SERVICE_SIZE          7

/*********************************************************************
 * TYPEDEFS
 */

// Fields in characteristic "STREAM_START"
//   Field "State" format: uint8, bits: 8

// Fields in characteristic "STREAM_INPUT"
//   Field "data" format: uint8[], bits: -1

// Fields in characteristic "STREAM_OUTPUT"
//   Field "data" format: uint8[], bits: -1

/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * Profile Callbacks
 */

// Callback when a characteristic value has changed
typedef void (*VogattChange_t)( uint16_t connHandle, uint16_t svcUuid, uint8_t paramID, uint8_t *pValue, uint16_t len );

typedef struct
{
  VogattChange_t        pfnChangeCb;     // Called when characteristic value changes
  VogattChange_t        pfnCfgChangeCb;  // Called when characteristic CCCD changes
} VogattCBs_t;



/*********************************************************************
 * API FUNCTIONS
 */


/*
 * Vogatt_AddService- Initializes the Vogatt service by registering
 *          GATT attributes with the GATT server.
 *
 *    rspTaskId - The ICall Task Id that should receive responses for Indications.
 */
extern bStatus_t Vogatt_AddService( uint8_t rspTaskId );

/*
 * Vogatt_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
extern bStatus_t Vogatt_RegisterAppCBs( VogattCBs_t *appCallbacks );

/*
 * Vogatt_SetParameter - Set a Vogatt parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t Vogatt_SetParameter( uint8_t param, uint16_t len, void *value );

/*
 * Vogatt_GetParameter - Get a Vogatt parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
extern bStatus_t Vogatt_GetParameter( uint8_t param, uint16_t *len, void *value );

/*********************************************************************
*********************************************************************/

#ifdef __cplusplus
}
#endif

#endif /* _VOGATT_H_ */

