/******************************************************************************
 * Filename:       VoGATT.c
 *
 * Description:    This file contains the implementation of the service.
 *
 *                 Generated by:
 *                 BDS version: 1.1.3139.0
 *                 Plugin:      Texas Instruments BLE SDK GATT Server plugin 1.0.9
 *                 Time:        Fri Sep 15 2017 01:07:25 GMT+07:00
 *

 * Copyright (c) 2015-2017, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **********************************************************************************/


/*********************************************************************
 * INCLUDES
 */
#include <string.h>

//#define xdc_runtime_Log_DISABLE_ALL 1  // Add to disable logs from this file
#include <xdc/runtime/Log.h>
#include <xdc/runtime/Diags.h>
#ifdef UARTLOG_ENABLE
#  include "UartLog.h"
#endif

#include <icall.h>
#include "util.h"
/* This Header file contains all BLE API and icall structure definition */
#include "icall_ble_api.h"

#include "vogatt.h"

/*********************************************************************
 * MACROS
 */

/*********************************************************************
 * CONSTANTS
 */

/*********************************************************************
 * TYPEDEFS
 */

/*********************************************************************
* GLOBAL VARIABLES
*/

// VoGATT Service UUID
CONST uint8_t VogattUUID[ATT_UUID_SIZE] =
{
  VOGATT_SERV_UUID_BASE128(VOGATT_SERV_UUID)
};

// STREAM_START UUID
CONST uint8_t v_STREAM_STARTUUID[ATT_UUID_SIZE] =
{
  V_STREAM_START_UUID_BASE128(V_STREAM_START_UUID)
};

// STREAM_INPUT UUID
CONST uint8_t v_STREAM_INPUTUUID[ATT_UUID_SIZE] =
{
  V_STREAM_INPUT_UUID_BASE128(V_STREAM_INPUT_UUID)
};

// STREAM_OUTPUT UUID
CONST uint8_t v_STREAM_OUTPUTUUID[ATT_UUID_SIZE] =
{
  V_STREAM_OUTPUT_UUID_BASE128(V_STREAM_OUTPUT_UUID)
};


/*********************************************************************
 * LOCAL VARIABLES
 */

static VogattCBs_t *pAppCBs = NULL;
static uint8_t v_icall_rsp_task_id = INVALID_TASK_ID;

/*********************************************************************
* Profile Attributes - variables
*/

// Service declaration
static CONST gattAttrType_t VogattDecl = { ATT_UUID_SIZE, VogattUUID };

// Characteristic "STREAM_START" Properties (for declaration)
static uint8_t v_STREAM_STARTProps = GATT_PROP_READ | GATT_PROP_WRITE | GATT_PROP_WRITE_NO_RSP;

// Characteristic "STREAM_START" Value variable
static uint8_t v_STREAM_STARTVal[V_STREAM_START_LEN] = {0};

// Length of data in characteristic "STREAM_START" Value variable, initialized to minimal size.
static uint16_t v_STREAM_STARTValLen = V_STREAM_START_LEN_MIN;



// Characteristic "STREAM_INPUT" Properties (for declaration)
static uint8_t v_STREAM_INPUTProps = GATT_PROP_WRITE | GATT_PROP_WRITE_NO_RSP;

// Characteristic "STREAM_INPUT" Value variable
static uint8_t v_STREAM_INPUTVal[V_STREAM_INPUT_LEN] = {0};

// Length of data in characteristic "STREAM_INPUT" Value variable, initialized to minimal size.
static uint16_t v_STREAM_INPUTValLen = V_STREAM_INPUT_LEN_MIN;



// Characteristic "STREAM_OUTPUT" Properties (for declaration)
static uint8_t v_STREAM_OUTPUTProps = GATT_PROP_NOTIFY | GATT_PROP_READ;

// Characteristic "STREAM_OUTPUT" Value variable
static uint8_t v_STREAM_OUTPUTVal[V_STREAM_OUTPUT_LEN] = {0};

// Length of data in characteristic "STREAM_OUTPUT" Value variable, initialized to minimal size.
static uint16_t v_STREAM_OUTPUTValLen = V_STREAM_OUTPUT_LEN_MIN;

// Characteristic "STREAM_OUTPUT" Client Characteristic Configuration Descriptor
static gattCharCfg_t *v_STREAM_OUTPUTConfig;



/*********************************************************************
* Profile Attributes - Table
*/

static gattAttribute_t VoGATTAttrTbl[] =
{
  // VoGATT Service Declaration
  {
    { ATT_BT_UUID_SIZE, primaryServiceUUID },
    GATT_PERMIT_READ,
    0,
    (uint8_t *)&VogattDecl
  },
    // STREAM_START Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &v_STREAM_STARTProps
    },
      // STREAM_START Characteristic Value
      {
        { ATT_UUID_SIZE, v_STREAM_STARTUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE | GATT_PERMIT_WRITE,
        0,
        v_STREAM_STARTVal
      },
    // STREAM_INPUT Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &v_STREAM_INPUTProps
    },
      // STREAM_INPUT Characteristic Value
      {
        { ATT_UUID_SIZE, v_STREAM_INPUTUUID },
        GATT_PERMIT_WRITE | GATT_PERMIT_WRITE,
        0,
        v_STREAM_INPUTVal
      },
    // STREAM_OUTPUT Characteristic Declaration
    {
      { ATT_BT_UUID_SIZE, characterUUID },
      GATT_PERMIT_READ,
      0,
      &v_STREAM_OUTPUTProps
    },
      // STREAM_OUTPUT Characteristic Value
      {
        { ATT_UUID_SIZE, v_STREAM_OUTPUTUUID },
        GATT_PERMIT_READ,
        0,
        v_STREAM_OUTPUTVal
      },
      // STREAM_OUTPUT CCCD
      {
        { ATT_BT_UUID_SIZE, clientCharCfgUUID },
        GATT_PERMIT_READ | GATT_PERMIT_WRITE,
        0,
        (uint8_t *)&v_STREAM_OUTPUTConfig
      },
};

/*********************************************************************
 * LOCAL FUNCTIONS
 */
static bStatus_t VoGATT_ReadAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                           uint8_t *pValue, uint16_t *pLen, uint16_t offset,
                                           uint16_t maxLen, uint8_t method );
static bStatus_t VoGATT_WriteAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                            uint8_t *pValue, uint16_t len, uint16_t offset,
                                            uint8_t method );

/*********************************************************************
 * PROFILE CALLBACKS
 */
// Simple Profile Service Callbacks
CONST gattServiceCBs_t VoGATTCBs =
{
  VoGATT_ReadAttrCB,  // Read callback function pointer
  VoGATT_WriteAttrCB, // Write callback function pointer
  NULL                       // Authorization callback function pointer
};

/*********************************************************************
* PUBLIC FUNCTIONS
*/

/*
 * Vogatt_AddService- Initializes the Vogatt service by registering
 *          GATT attributes with the GATT server.
 *
 *    rspTaskId - The ICall Task Id that should receive responses for Indications.
 */
extern bStatus_t Vogatt_AddService( uint8_t rspTaskId )
{
  uint8_t status;

  // Allocate Client Characteristic Configuration table
  v_STREAM_OUTPUTConfig = (gattCharCfg_t *)ICall_malloc( sizeof(gattCharCfg_t) * linkDBNumConns );
  if ( v_STREAM_OUTPUTConfig == NULL )
  {
    return ( bleMemAllocError );
  }

  // Initialize Client Characteristic Configuration attributes
  GATTServApp_InitCharCfg( INVALID_CONNHANDLE, v_STREAM_OUTPUTConfig );
  // Register GATT attribute list and CBs with GATT Server App
  status = GATTServApp_RegisterService( VoGATTAttrTbl,
                                        GATT_NUM_ATTRS( VoGATTAttrTbl ),
                                        GATT_MAX_ENCRYPT_KEY_SIZE,
                                        &VoGATTCBs );
  Log_info1("Registered service, %d attributes", (IArg)GATT_NUM_ATTRS( VoGATTAttrTbl ));
  v_icall_rsp_task_id = rspTaskId;

  return ( status );
}

/*
 * Vogatt_RegisterAppCBs - Registers the application callback function.
 *                    Only call this function once.
 *
 *    appCallbacks - pointer to application callbacks.
 */
bStatus_t Vogatt_RegisterAppCBs( VogattCBs_t *appCallbacks )
{
  if ( appCallbacks )
  {
    pAppCBs = appCallbacks;
    Log_info1("Registered callbacks to application. Struct %p", (IArg)appCallbacks);
    return ( SUCCESS );
  }
  else
  {
    Log_warning0("Null pointer given for app callbacks.");
    return ( FAILURE );
  }
}

/*
 * Vogatt_SetParameter - Set a Vogatt parameter.
 *
 *    param - Profile parameter ID
 *    len   - length of data to write
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
bStatus_t Vogatt_SetParameter( uint8_t param, uint16_t len, void *value )
{
  bStatus_t ret = SUCCESS;
  uint8_t  *pAttrVal;
  uint16_t *pValLen;
  uint16_t valMinLen;
  uint16_t valMaxLen;
  uint8_t sendNotiInd = FALSE;
  gattCharCfg_t *attrConfig;
  uint8_t needAuth;

  switch ( param )
  {
    case V_STREAM_START_ID:
      pAttrVal  =  v_STREAM_STARTVal;
      pValLen   = &v_STREAM_STARTValLen;
      valMinLen =  V_STREAM_START_LEN_MIN;
      valMaxLen =  V_STREAM_START_LEN;
      Log_info2("SetParameter : %s len: %d", (IArg)"STREAM_START", (IArg)len);
      break;

    case V_STREAM_OUTPUT_ID:
      pAttrVal  =  v_STREAM_OUTPUTVal;
      pValLen   = &v_STREAM_OUTPUTValLen;
      valMinLen =  V_STREAM_OUTPUT_LEN_MIN;
      valMaxLen =  V_STREAM_OUTPUT_LEN;
      sendNotiInd = TRUE;
      attrConfig  = v_STREAM_OUTPUTConfig;
      needAuth    = FALSE; // Change if authenticated link is required for sending.
      Log_info2("SetParameter : %s len: %d", (IArg)"STREAM_OUTPUT", (IArg)len);
      break;

    default:
      Log_error1("SetParameter: Parameter #%d not valid.", (IArg)param);
      return INVALIDPARAMETER;
  }

  // Check bounds, update value and send notification or indication if possible.
  if ( len <= valMaxLen && len >= valMinLen )
  {
    memcpy(pAttrVal, value, len);
    *pValLen = len; // Update length for read and get.

    if (sendNotiInd)
    {
      Log_info2("Transmitting noti/ind- connHandle %d, %s", (IArg)attrConfig[0].connHandle,
                                                    (IArg)( (attrConfig[0].value==0)?"Noti/ind disabled":
                                                    (attrConfig[0].value==1)?"Notification enabled":
                                                     "Indication enabled" ) );
      // Try to send notification.
      GATTServApp_ProcessCharCfg( attrConfig, pAttrVal, needAuth,
                                  VoGATTAttrTbl, GATT_NUM_ATTRS( VoGATTAttrTbl ),
                                  v_icall_rsp_task_id,  VoGATT_ReadAttrCB);
    }
  }
  else
  {
    Log_error3("Length outside bounds: Len: %d MinLen: %d MaxLen: %d.", (IArg)len, (IArg)valMinLen, (IArg)valMaxLen);
    ret = bleInvalidRange;
  }

  return ret;
}


/*
 * Vogatt_GetParameter - Get a Vogatt parameter.
 *
 *    param - Profile parameter ID
 *    len   - pointer to a variable that contains the maximum length that can be written to *value.
              After the call, this value will contain the actual returned length.
 *    value - pointer to data to write.  This is dependent on
 *            the parameter ID and may be cast to the appropriate
 *            data type (example: data type of uint16_t will be cast to
 *            uint16_t pointer).
 */
bStatus_t Vogatt_GetParameter( uint8_t param, uint16_t *len, void *value )
{
  bStatus_t ret = SUCCESS;
  switch ( param )
  {
    case V_STREAM_START_ID:
      *len = MIN(*len, v_STREAM_STARTValLen);
      memcpy(value, v_STREAM_STARTVal, *len);
      Log_info2("GetParameter : %s returning %d bytes", (IArg)"STREAM_START", (IArg)*len);
      break;

    case V_STREAM_INPUT_ID:
      *len = MIN(*len, v_STREAM_INPUTValLen);
      memcpy(value, v_STREAM_INPUTVal, *len);
      Log_info2("GetParameter : %s returning %d bytes", (IArg)"STREAM_INPUT", (IArg)*len);
      break;

    default:
      Log_error1("GetParameter: Parameter #%d not valid.", (IArg)param);
      ret = INVALIDPARAMETER;
      break;
  }
  return ret;
}

/*********************************************************************
 * @internal
 * @fn          VoGATT_findCharParamId
 *
 * @brief       Find the logical param id of an attribute in the service's attr table.
 *
 *              Works only for Characteristic Value attributes and
 *              Client Characteristic Configuration Descriptor attributes.
 *
 * @param       pAttr - pointer to attribute
 *
 * @return      uint8_t paramID (ref VoGATT.h) or 0xFF if not found.
 */
static uint8_t VoGATT_findCharParamId(gattAttribute_t *pAttr)
{
  // Is this a Client Characteristic Configuration Descriptor?
  if (ATT_BT_UUID_SIZE == pAttr->type.len && GATT_CLIENT_CHAR_CFG_UUID == *(uint16_t *)pAttr->type.uuid)
    return VoGATT_findCharParamId(pAttr - 1); // Assume the value attribute precedes CCCD and recurse

  // Is this attribute in "STREAM_START"?
  else if ( ATT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, v_STREAM_STARTUUID, pAttr->type.len))
    return V_STREAM_START_ID;

  // Is this attribute in "STREAM_INPUT"?
  else if ( ATT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, v_STREAM_INPUTUUID, pAttr->type.len))
    return V_STREAM_INPUT_ID;

  // Is this attribute in "STREAM_OUTPUT"?
  else if ( ATT_UUID_SIZE == pAttr->type.len && !memcmp(pAttr->type.uuid, v_STREAM_OUTPUTUUID, pAttr->type.len))
    return V_STREAM_OUTPUT_ID;

  else
    return 0xFF; // Not found. Return invalid.
}

/*********************************************************************
 * @fn          VoGATT_ReadAttrCB
 *
 * @brief       Read an attribute.
 *
 * @param       connHandle - connection message was received on
 * @param       pAttr - pointer to attribute
 * @param       pValue - pointer to data to be read
 * @param       pLen - length of data to be read
 * @param       offset - offset of the first octet to be read
 * @param       maxLen - maximum length of data to be read
 * @param       method - type of read message
 *
 * @return      SUCCESS, blePending or Failure
 */
static bStatus_t VoGATT_ReadAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                       uint8_t *pValue, uint16_t *pLen, uint16_t offset,
                                       uint16_t maxLen, uint8_t method )
{
  bStatus_t status = SUCCESS;
  uint16_t valueLen;
  uint8_t paramID = 0xFF;

  // Find settings for the characteristic to be read.
  paramID = VoGATT_findCharParamId( pAttr );
  switch ( paramID )
  {
    case V_STREAM_START_ID:
      valueLen = v_STREAM_STARTValLen;

      Log_info4("ReadAttrCB : %s connHandle: %d offset: %d method: 0x%02x",
                 (IArg)"STREAM_START",
                 (IArg)connHandle,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for STREAM_START can be inserted here */
      break;

    case V_STREAM_OUTPUT_ID:
      valueLen = v_STREAM_OUTPUTValLen;

      Log_info4("ReadAttrCB : %s connHandle: %d offset: %d method: 0x%02x",
                 (IArg)"STREAM_OUTPUT",
                 (IArg)connHandle,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for STREAM_OUTPUT can be inserted here */
      break;

    default:
      Log_error0("Attribute was not found.");
      return ATT_ERR_ATTR_NOT_FOUND;
  }
  // Check bounds and return the value
  if ( offset > valueLen )  // Prevent malicious ATT ReadBlob offsets.
  {
    Log_error0("An invalid offset was requested.");
    status = ATT_ERR_INVALID_OFFSET;
  }
  else
  {
    *pLen = MIN(maxLen, valueLen - offset);  // Transmit as much as possible
    memcpy(pValue, pAttr->pValue + offset, *pLen);
  }

  return status;
}

/*********************************************************************
 * @fn      VoGATT_WriteAttrCB
 *
 * @brief   Validate attribute data prior to a write operation
 *
 * @param   connHandle - connection message was received on
 * @param   pAttr - pointer to attribute
 * @param   pValue - pointer to data to be written
 * @param   len - length of data
 * @param   offset - offset of the first octet to be written
 * @param   method - type of write message
 *
 * @return  SUCCESS, blePending or Failure
 */
static bStatus_t VoGATT_WriteAttrCB( uint16_t connHandle, gattAttribute_t *pAttr,
                                        uint8_t *pValue, uint16_t len, uint16_t offset,
                                        uint8_t method )
{
  bStatus_t status  = SUCCESS;
  uint8_t   paramID = 0xFF;
  uint8_t   changeParamID = 0xFF;
  uint16_t writeLenMin;
  uint16_t writeLenMax;
  uint16_t *pValueLenVar;

  // See if request is regarding a Client Characterisic Configuration
  if (ATT_BT_UUID_SIZE == pAttr->type.len && GATT_CLIENT_CHAR_CFG_UUID == *(uint16_t *)pAttr->type.uuid)
  {
    // Allow notification and indication, but do not check if really allowed per CCCD.
    status = GATTServApp_ProcessCCCWriteReq( connHandle, pAttr, pValue, len,
                                             offset, GATT_CLIENT_CFG_NOTIFY |
                                                     GATT_CLIENT_CFG_INDICATE );
    if (SUCCESS == status && pAppCBs && pAppCBs->pfnCfgChangeCb)
       pAppCBs->pfnCfgChangeCb( connHandle, VOGATT_SERV_UUID,
                                VoGATT_findCharParamId(pAttr), pValue, len );

     return status;
  }

  // Find settings for the characteristic to be written.
  paramID = VoGATT_findCharParamId( pAttr );
  switch ( paramID )
  {
    case V_STREAM_START_ID:
      writeLenMin  = V_STREAM_START_LEN_MIN;
      writeLenMax  = V_STREAM_START_LEN;
      pValueLenVar = &v_STREAM_STARTValLen;

      Log_info5("WriteAttrCB : %s connHandle(%d) len(%d) offset(%d) method(0x%02x)",
                 (IArg)"STREAM_START",
                 (IArg)connHandle,
                 (IArg)len,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for STREAM_START can be inserted here */
      break;

    case V_STREAM_INPUT_ID:
      writeLenMin  = V_STREAM_INPUT_LEN_MIN;
      writeLenMax  = V_STREAM_INPUT_LEN;
      pValueLenVar = &v_STREAM_INPUTValLen;

      Log_info5("WriteAttrCB : %s connHandle(%d) len(%d) offset(%d) method(0x%02x)",
                 (IArg)"STREAM_INPUT",
                 (IArg)connHandle,
                 (IArg)len,
                 (IArg)offset,
                 (IArg)method);
      /* Other considerations for STREAM_INPUT can be inserted here */
      break;

    default:
      Log_error0("Attribute was not found.");
      return ATT_ERR_ATTR_NOT_FOUND;
  }
  // Check whether the length is within bounds.
  if ( offset >= writeLenMax )
  {
    Log_error0("An invalid offset was requested.");
    status = ATT_ERR_INVALID_OFFSET;
  }
  else if ( offset + len > writeLenMax )
  {
    Log_error0("Invalid value length was received.");
    status = ATT_ERR_INVALID_VALUE_SIZE;
  }
  else if ( offset + len < writeLenMin && ( method == ATT_EXECUTE_WRITE_REQ || method == ATT_WRITE_REQ ) )
  {
    // Refuse writes that are lower than minimum.
    // Note: Cannot determine if a Reliable Write (to several chars) is finished, so those will
    //       only be refused if this attribute is the last in the queue (method is execute).
    //       Otherwise, reliable writes are accepted and parsed piecemeal.
    Log_error0("Invalid value length was received.");
    status = ATT_ERR_INVALID_VALUE_SIZE;
  }
  else
  {
    // Copy pValue into the variable we point to from the attribute table.
    memcpy(pAttr->pValue + offset, pValue, len);

    // Only notify application and update length if enough data is written.
    //
    // Note: If reliable writes are used (meaning several attributes are written to using ATT PrepareWrite),
    //       the application will get a callback for every write with an offset + len larger than _LEN_MIN.
    // Note: For Long Writes (ATT Prepare + Execute towards only one attribute) only one callback will be issued,
    //       because the write fragments are concatenated before being sent here.
    if ( offset + len >= writeLenMin )
    {
      changeParamID = paramID;
      *pValueLenVar = offset + len; // Update data length.
    }
  }

  // Let the application know something changed (if it did) by using the
  // callback it registered earlier (if it did).
  if (changeParamID != 0xFF)
    if ( pAppCBs && pAppCBs->pfnChangeCb )
      pAppCBs->pfnChangeCb( connHandle, VOGATT_SERV_UUID, paramID, pValue, len+offset ); // Call app function from stack task context.

  return status;
}
